#tools installer
#v0.1
#creat by RaMsY

from resource import *
import os
import sys
import time
def main():
    while True:
    	             r = input("\033[1;32m  RaMsY=> ")
    	             if r == 'help':
    	             	print("\033[1;36m  commands             explication       ")
    	             	print("\033[1;33m  show tools      show all name of tooles")
    	             	print(" install<name of tool>  use it to install a tools")
    	             	print("    exit        use it the exit the script")
    	             elif r == 'show tools':
    	             	time.sleep(1)
    	             	print("\033[1;35m nmap")
    	             	print("RED_HAWK")
    	             	print("D-TECT")
    	             	print("sqlmap")
    	             	print("infoga")
    	             	print("ReconDog")
    	             	print("androZenmap")
    	             	print("sqlmate")
    	             	print("AstraNmap")
    	             	print("weemen")
    	             	print("Easymap")
    	             	print("xd3v")
    	             	print("Crips")
    	             	print("sir")
    	             	print("xshell")
    	             	print("EvilURL")
    	             	print("Striker")
    	             	print("DSSS")
    	             	print("sqliv")
    	             	print("sqlscan")
    	             	print("Wordpress")
    	             	print("WPScan")
    	             	print("termux-wordpresscan")
    	             	print("routersploit")  
    	             	print("torhammer")
    	             	print("slowloris")
    	             	print("fl00d12")
    	             	print("goldeneye")
    	             	print("xerxes")
    	             	print("Planetwork-DDOS")
    	             	print("hydra")
    	             	print("Black-Hydra")
    	             	print("cupp")
    	             	print("asu")
    	             	print("Hash-Buster")
    	             	print("instaHack")
    	             	print("indonesian-wordlist")
    	             	print("Facebook Brute Force 3")
    	             	print("WebDA")
    	             	print("Webdav Mass Exploiter")
    	             	print("sqldump")
    	             	print("Websploit")
    	             	print("Metasploit")
    	             	print("Commix")
    	             	print("Brutal")
    	             	print("KnockMail")
    	             	print("Hac")
    	             	print("Rang3r")
    	             	print("SH33LL")
    	             	print("Social-Engineering")
    	             	print("SpiderBot")
    	             	print("ngrok")
    	             	print("sudo")
    	             	print("Ubuntu")
    	             	print("fedora")
    	             	print("Nethunter")
    	             	print("BlackBox")
    	             	print("XAttacker")
    	             	print("VCRT")
    	             	print("SocialFish")
    	             	print("ECode")
    	             	print("XSStrike")
    	             	print("Breacher")
    	             	print("Termux-Styling")
    	             	print("TXTool")
    	             	print("PassGen")
    	             	print("OWScan")
    	             	print("santet-online")
    	             	print("SpazSMS")
    	             	print("Hasher")
    	             	print("Hash-Generator")
    	             	print("ko-dork")
    	             	print("snitch")
    	             	print("OSIF")
    	             	print("nk26")
    	             	print("Devploit")
    	             	print("Hasherdotid")
    	             	print("Namechk")
    	             	print("xl-py")
    	             	print("Beanshell")
    	             	print("Crunch")
    	             	print("Exploitation")
    	             	print("Textr")
    	             	print("ApSca")
    	             	print("amox")
    	             	print("FaDe")
    	             	print("GINF")
    	             	print("AUXILE")
    	             	print("inther")
    	             	print("HPB")
    	             	print("FMBrute")
    	             	print("HashID")
    	             	print("GPS Tracking")
    	             	print("PRET")
    	             	print("Atlas")
    	             	print("Hashcat")
    	             	print("LiteOTP")
    	             	print("FBBrute")
    	             	print("fim")
    	             	print("RShell")
    	             	print("TermPyter")
    	             	print("MaxSubdoFinder")
    	             	print("jadx")
    	             	print("pwnedOrNot")
    	             	print("Mac-Lookup")
    	             	print("F4K3")
    	             	print("Katak")
    	             	print("heroku")
    	             	print("google")
    	             	print("BillCypher")
    	             	print("vbug")
    	             	print("kojawaf")
    	             	print("aircrackng")
    	             	print("ettercap")
    	             	print("ccgen")
    	             	print("ddcrypt")
    	             	print("dnsrecon")
    	             	print("zphisher")
    	             	print("apkto")
    	             	print("uncompyle6")
    	             	print("wifite")
    	             	print("Parrot")
    	             	print("Arch Linux")
    	             	print("tshark")
    	             	print("dos2unix")
    	             	print("exiftool")
    	             	print("iconv")
    	             	print("mediainfo")
    	             	print("pdfinfo")
    	             	print("tcpdump")
    	             	print("hping3")
    	             	print("DbDat")
    	             	print("NoSQLMap")
    	             	print("audit_couchdb")
    	             	print("mongoaudit")
    	             	print("Wifiphisher")
    	             	print("sherlock")
    	             	print("shc")
    	             	print("steghide")
    	             	print("tesseract")
    	             	print("sleuthkit")
    	             	print("Octave")
    	             	print("fpcompiler")
    	             	print("numpy")
    	             	print("userrecon")
    	             	print("Mr.SIP")
    	             	print("TM-scanner")
    	             	print("xss-payload-list")
    	             elif r == 'install RED_HAWK':
    	              red_hawk()
    	             elif r == 'install D-TECT':
    	              dtect()
    	             elif r == 'install sqlmap':
    	              sqlmap()
    	             elif r == 'install infoga':
    	              infoga()
    	             elif r == 'install ReconDog':
    	              reconDog()
    	             elif r == 'install androZenmap':
    	              androZenmap()
    	             elif r == 'install sqlmate':
    	              sqlmate()
    	             elif r == 'install AstraNmap':
    	               astraNmap() 
    	             elif r == 'install weemen':
    	               weeman()
    	             elif r == 'install Easymap':
    	               easyMap()
    	             elif r == 'install xd3v':
    	               xd3v()
    	             elif r == 'install Crips':
    	               crips()
    	             elif r == 'install sir':
    	               sir()
    	             elif r == 'install xshell':
    	               xshell()
    	             elif r == 'install EvilURL':
    	               evilURL()
    	             elif r == 'install Striker':
    	               striker()
    	             elif r == 'install DSSS':
    	               dsss()
    	             elif r == 'install sqliv':
    	               sqliv()
    	             elif r == 'install sqlscan':
    	               sqlscan()
    	             elif r == 'install Wordpress':
    	               wordpreSScan()
    	             elif r == 'install WPScan':
    	               wpscan()
    	             elif r == 'install termux-wordpresscan':
    	               wordpresscan()
    	             elif r == 'install routersploit':
    	               routersploit()
    	             elif r == 'install torhammer':
    	               torshammer()
    	             elif r == 'exit':
    	             	print("\033[1;34m bay bay")
    	             	sys.exit()
    	             else :
    	              print("\033[1;31m ERROR: Wrong Input")
    	              time.sleep(1)
       			    
       			    
       			    
if __name__ == "__main__":
	main()    	                 	            
